<script type="text/javascript">
jQuery(document).ready(function($) {
    $('.am-tabs li:has(ul) > a').prepend(
        $('<div></div>').addClass('arrow')
    );
});
</script>
<div class="am-tabs">
<?php
$m = new Am_View_Helper_Menu();
$m->setView($this);

echo "<div class=\"navbar\">";
echo "<div class=\"navbar-inner\">";
echo "<a class=\"brand\" href=\"/amember4/member\">Membership</a>";

echo $m->renderMenu($this->di->navigationUser,
    array(
        'ulClass' => 'nav',
        'activeClass' => 'active',
        'normalClass' => 'normal',
        'disabledClass' => 'disabled',
        'maxDepth' => 1,
    )
);

echo "</div></div>";

?>
</div>
