<?php
	$title=___('Payment Failed'); $this->setLayout('layout.phtml');
	include $this->_script('_error.phtml');
?>

<div class="cancel-paysystems">
	<span class="error"><?php __e('An error occurred while handling your payment.') ?></span>
	
	<?php if (count($this->paysystems) > 1): ?>
		<p>You may optionally choose a different payment processor before trying again. Alternatively, you may cancel the registration process.</p>
	<?php else: ?>
		<p>You may attempt to make a payment again. Alternatively, you may cancel the registration process.</p>
	<?php endif; ?>

	<form class="form-horizontal" method="post" action="<?php echo REL_ROOT_URL?>/cancel/repeat">
		<?php foreach ($this->paysystems as $ps)
			$string = <<<'HTML'
				<div class="control-group">
					<label class="radio">
						<input type="radio" name="paysys_id" value="%1$s" id="paysys-%1$s"/>
						%2$s - %3$s
					</label>
				</div>
HTML;
			printf($string, $ps['paysys_id'], $ps['title'], $ps['description']);
		?>
		<input type="hidden" name="id" value="<?php echo $this->escape($id) ?>" />
		<input class="btn btn-primary btn-large" type="submit" name="do" value="<?php __e("Make Payment")?>" />
		<a href="/amember4/logout" class="btn btn-large">Cancel Registration</a>
	</form>
</div>
